### PR TITLE
READMe Sanaz

### PR DESCRIPTION
**Pull request by SanazNajiyan**

### CODE REVIEW

**Review by TheMinefreak23 — CHANGES_REQUESTED** [review]
Information such as examples of correct parameters should be included in the docstrings for the functions themselves, as well as short explanations on how to use (should it be necessary). Further in-depth information can be stored separately in e.g. a repo wiki, but preferably not in a readme file deep inside the source code. Most of this readme content can be in the code instead. We can keep some info in the readme for now, but please try to keep it to the absolutely necessary and know that we'll have to move it to a wiki eventually.

**Comment by SanazNajiyan** [comment]
> Information such as examples of correct parameters should be included in the docstrings for the functions themselves, as well as short explanations on how to use (should it be necessary). Further in-depth information can be stored separately in e.g. a repo wiki, but preferably not in a readme file deep inside the source code. Most of this readme content can be in the code instead. We can keep some info in the readme for now, but please try to keep it to the absolutely necessary and know that we'll have to move it to a wiki eventually.



> Information such as examples of correct parameters should be included in the docstrings for the functions themselves, as well as short explanations on how to use (should it be necessary). Further in-depth information can be stored separately in e.g. a repo wiki, but preferably not in a readme file deep inside the source code. Most of this readme content can be in the code instead. We can keep some info in the readme for now, but please try to keep it to the absolutely necessary and know that we'll have to move it to a wiki eventually.

I already put doc strings in the code. I understand, the readme indeed will move into wiki of the repo later. Yet, for now I wanted to make a sort of manual to make it quick for the teammates who want to test things in dataloaders' folder since I already received some questions which could easily be referred to my readme. I am gradually making it a wiki and make sure to eventually remove it.

**Comment by SanazNajiyan** [comment]
> > Information such as examples of correct parameters should be included in the docstrings for the functions themselves, as well as short explanations on how to use (should it be necessary). Further in-depth information can be stored separately in e.g. a repo wiki, but preferably not in a readme file deep inside the source code. Most of this readme content can be in the code instead. We can keep some info in the readme for now, but please try to keep it to the absolutely necessary and know that we'll have to move it to a wiki eventually.
> 
> I already put doc strings in the code. I understand, the readme indeed will move into wiki of the repo later. Yet, for now I wanted to make a sort of manual to make it quick for the teammates who want to test things in dataloaders' folder since I already received some questions which could easily be referred to my readme. I am gradually making it a wiki and make sure to eventually remove it.

Btw, do we have wiki in repo? I didn't find it. I could move it there otherwise.

**Comment by TheMinefreak23** [comment]
Preferably we focus on the comments for now, since we can then automatically generate the wiki. I'm still of the opinion that as pretty much all information in this readme can be either included in docstrings or demonstrated through tests. As such, please try making the comments PEP 257 compliant, as per the link I put up in the Discord server, and write some unit tests if you want to show examples of usage (since we need to write these regardless).

**Comment by SanazNajiyan** [comment]
> Preferably we focus on the comments for now, since we can then automatically generate the wiki. I'm still of the opinion that as pretty much all information in this readme can be either included in docstrings or demonstrated through tests. As such, please try making the comments PEP 257 compliant, as per the link I put up in the Discord server, and write some unit tests if you want to show examples of usage (since we need to write these regardless).

That's fine. I will keep it locally for now . later I try to write unit tests..

**Pull request closed without merging**
