### PR TITLE
filter folder _age, gender, country, base.py

### PR DESCRIPTION
**Pull request by SanazNajiyan**

### CODE REVIEW

**Review by TheMinefreak23 — CHANGES_REQUESTED** [review]
Please make sure pydocstyle agrees with your comments, and that the (partial) linter throws no errors. Also at this point in the project I'd request that you don't push new functionality without writing unit tests for it. This way we can assure the code works as we intend it to. EDIT: Also please exclude the roderickl.py file from your committed files.

**Comment by SanazNajiyan** [comment]
Hi, the modules I worked on I did pylint and seemed ok. if there were major issues plz send me the snap shot. 
The rest of the points , I agree and will work on em

**Comment by TheMinefreak23** [comment]
> if there were major issues plz send me the snap shot.

If you look at the failed checks on this page, you can click details on the right and see the output of the linter.
image

**Comment by sivd** [comment]
the linting still fails because there is a "roderickl.py" file in there, that should not be pushed to dev, delete it pls

**Comment by TheMinefreak23** [comment]
It seems the linter is still failing because of your unit test files, which I'm guessing you missed because they're outside the src directory. The changes seem relatively minor, so I'll fix them for you and merge afterwards. Thanks for incorporating the requested changes :)

**Review by TheMinefreak23 — APPROVED** [review]

**Pull request merged**
